language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist
